apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: oidc
  annotations:
    kubernetes.io/ingress.class: "kong"
    #labels:
    #global: "false"
    #disabled: false # optionally disable the plugin in Kong
plugin: oidc
config: # configuration for the plugin
  client_id: kong # Realm
  client_secret: 47c84a80-cb38-467c-ad16-da4db3589b58  # Client Secret Copied
  realm: demo
  discovery: https://172.20.105.225/auth/realms/demo/.well-known/openid-configuration # OpenID Endpoint Configuration Copied
  scope: openid
  redirect_after_logout_uri : https://172.20.105.225/auth/realms/demo/protocol/openid-connect/logout?redirect_uri=https://172.20.105.225/sample-angular/
